"""自己完結HTML差分レポート(単一ファイル・依存なし・フィルタ内蔵)。

メール添付やチャット共有向け。受け取った人はブラウザで開くだけで
状態フィルタ・検索付きの差分結果を閲覧できる。
"""
from __future__ import annotations

import html
import json

from .model import DiffResult
from .upsert import build_report_table
from .verify import build_verification

_MAX_ROWS = 50_000


def build_html_report(diff: DiffResult, *, only_b_is_error: bool = True) -> str:
    report = build_report_table(diff)
    v = build_verification(diff, only_b_is_error=only_b_is_error)
    truncated = len(report.rows) > _MAX_ROWS
    rows = report.rows[:_MAX_ROWS]
    data = {"columns": report.columns, "rows": rows}
    s = diff.summary
    verdict_class = "ok" if v.passed else "ng"
    verdict_text = "✔ 投入OK(全件一致)" if v.passed else "✖ 要確認(差異あり)"
    problems = "".join(f"<li>{html.escape(p)}</li>" for p in v.problems)

    return f"""<!DOCTYPE html>
<html lang="ja"><head><meta charset="utf-8">
<title>DiffDesk 差分レポート — {html.escape(diff.name_a)} ⇔ {html.escape(diff.name_b)}</title>
<style>
body{{font-family:"Yu Gothic UI","Hiragino Sans",sans-serif;font-size:13px;margin:0;background:#ece9e2;color:#222}}
header{{background:#3d4a41;color:#fff;padding:8px 14px;font-weight:bold}}
main{{padding:12px;max-width:1400px;margin:0 auto}}
.verdict{{padding:10px 14px;font-size:16px;font-weight:bold;border:1px solid;margin-bottom:10px}}
.verdict.ok{{background:#d9edd5;border-color:#4e8a47;color:#1f4a1b}}
.verdict.ng{{background:#f4d9d5;border-color:#b05248;color:#6d241b}}
.stats{{display:flex;gap:18px;flex-wrap:wrap;margin-bottom:10px;background:#f7f5f0;border:1px solid #b7b2a6;padding:8px 12px}}
.stats b{{font-size:15px}}
.bar{{display:flex;gap:8px;align-items:center;margin-bottom:8px;flex-wrap:wrap}}
button{{border:1px solid #7a766c;background:#e8e5dd;padding:4px 12px;cursor:pointer;font-size:12px}}
button.on{{background:#3d4a41;color:#fff}}
input{{border:1px solid #948f83;padding:4px 8px;font-size:12px}}
table{{border-collapse:collapse;width:100%;background:#fff;font-size:12px}}
th,td{{border:1px solid #d4d0c6;padding:3px 8px;text-align:left;white-space:nowrap;max-width:380px;overflow:hidden;text-overflow:ellipsis}}
th{{background:#d8d4c9;position:sticky;top:0}}
tr.st-変更 td:first-child{{background:#ffefad}}
tr.st-Aのみ td{{background:#d9edd5}}
tr.st-Bのみ td{{background:#f4d9d5}}
.wrap{{overflow:auto;max-height:75vh;border:1px solid #b7b2a6}}
footer{{padding:8px 14px;color:#6d675c;font-size:11px}}
ul{{margin:4px 0}}
</style></head><body>
<header>DiffDesk 差分レポート — {html.escape(diff.name_a)} ⇔ {html.escape(diff.name_b)}</header>
<main>
<div class="verdict {verdict_class}">{verdict_text}</div>
<div class="stats">
<span>Aのみ <b>{s['only_a']}</b></span><span>変更 <b>{s['changed']}</b></span>
<span>Bのみ <b>{s['only_b']}</b></span><span>一致 <b>{s['same']}</b></span>
<span>キー重複 A:<b>{s['duplicates_a']}</b> B:<b>{s['duplicates_b']}</b></span>
</div>
<ul>{problems}</ul>
<div class="bar">
<span>表示:</span>
<button class="f on" data-f="">全て</button>
<button class="f" data-f="Aのみ">Aのみ</button>
<button class="f" data-f="Bのみ">Bのみ</button>
<button class="f" data-f="変更">変更</button>
<button class="f" data-f="一致">一致</button>
<input id="q" placeholder="検索(全列部分一致)" size="28">
<span id="count"></span>
</div>
<div class="wrap"><table id="t"><thead></thead><tbody></tbody></table></div>
{"<p>※ 表示は先頭" + format(_MAX_ROWS, ",") + "行までです。</p>" if truncated else ""}
</main>
<footer>Generated by DiffDesk</footer>
<script>
const DATA = {json.dumps(data, ensure_ascii=False)};
let filter = "", q = "";
const esc = s => String(s).replace(/[&<>"]/g, c => ({{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}})[c]);
document.querySelector("#t thead").innerHTML =
  "<tr>" + DATA.columns.map(c => "<th>" + esc(c) + "</th>").join("") + "</tr>";
function render() {{
  const ql = q.toLowerCase();
  const rows = DATA.rows.filter(r =>
    (!filter || r[0] === filter) &&
    (!ql || r.some(v => String(v).toLowerCase().includes(ql))));
  document.querySelector("#t tbody").innerHTML = rows.slice(0, 2000).map(r =>
    "<tr class='st-" + esc(r[0]) + "'>" + r.map(v => "<td>" + esc(v) + "</td>").join("") + "</tr>").join("");
  document.querySelector("#count").textContent =
    rows.length + "件" + (rows.length > 2000 ? "(先頭2000件を表示)" : "");
}}
document.querySelectorAll(".f").forEach(b => b.onclick = () => {{
  filter = b.dataset.f;
  document.querySelectorAll(".f").forEach(x => x.classList.toggle("on", x === b));
  render();
}});
document.querySelector("#q").oninput = e => {{ q = e.target.value; render(); }};
render();
</script>
</body></html>"""
