"""Salesforce Data Loader 向けの出力生成。

前提: ファイルA = 正マスタ、ファイルB = Salesforceエクスポート。
- アップサートCSV: only_a(insert) + changed(update) をAの値で出力。
  ヘッダーは各ペアの sf_field(未指定なら col_b)。
- 削除CSV: only_b の行から Id 列のみを出力。
- .sdl: Data Loader のフィールドマッピング定義(Javaプロパティ形式)。
"""
from __future__ import annotations

from .model import ColumnPair, DiffDeskError, DiffResult, Table

UPSERT_STATUSES = ("only_a", "changed")


def _find_pair(diff: DiffResult, col_a: str) -> ColumnPair:
    for p in diff.mapping.pairs:
        if p.col_a == col_a:
            return p
    raise DiffDeskError(f"マッピングに列がありません: {col_a}", column=col_a)


def build_upsert_table(diff: DiffResult, *, external_id_col_a: str,
                       include: set[str] | None = None) -> Table:
    """アップサート用Tableを生成する。external_id_col_a はキーペアのA側列名。"""
    if include is None:
        include = set(UPSERT_STATUSES)
    if not include:
        raise DiffDeskError(
            "アップサート対象が空です。insert(Aのみ)かupdate(変更)の"
            "少なくとも一方を含めてください。")
    bad = include - set(UPSERT_STATUSES)
    if bad:
        raise DiffDeskError(f"アップサート対象にできない状態です: {sorted(bad)}")
    ext = _find_pair(diff, external_id_col_a)
    if not ext.is_key:
        raise DiffDeskError(
            f"外部ID列はキーに指定されたペアから選んでください: {external_id_col_a}",
            column=external_id_col_a,
        )
    cols_a = [p.col_a for p in diff.mapping.pairs]
    headers = [p.output_field for p in diff.mapping.pairs]
    if len(set(headers)) != len(headers):
        raise DiffDeskError("出力ヘッダー(Salesforce項目名)が重複しています。",
                          headers=headers)
    rows = [list(rd.row_a) for rd in diff.rows
            if rd.status in include and rd.row_a is not None and not rd.known]
    return Table(columns=headers, rows=rows, name="upsert")


def build_delete_table(diff: DiffResult, *, id_col_b: str = "Id") -> Table:
    """削除用Table(Bのみ行のId列)を生成する。id_col_b はB側の列名。"""
    idx = None
    for i, p in enumerate(diff.mapping.pairs):
        if p.col_b == id_col_b:
            idx = i
            break
    if idx is None:
        raise DiffDeskError(
            f"削除用のID列がマッピングにありません: {id_col_b}"
            "(B側のId列をマッピングに含めてください)",
            column=id_col_b,
        )
    rows = []
    for rd in diff.rows:
        if rd.status == "only_b" and rd.row_b is not None and not rd.known:
            v = rd.row_b[idx]
            if v.strip():
                rows.append([v])
    return Table(columns=["Id"], rows=rows, name="delete")


def _sdl_escape(s: str) -> str:
    """Javaプロパティ形式のエスケープ(非ASCIIは\\uXXXX)。"""
    out = []
    for ch in s:
        if ch in "=:\\ #!":
            out.append("\\" + ch)
        elif ord(ch) > 0x7E:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return "".join(out)


def build_sdl(diff: DiffResult) -> str:
    """アップサートCSV(ヘッダー=output_field)に対応する.sdl内容を返す。"""
    lines = ["# Salesforce Data Loader mapping (generated by diffdesk)"]
    for p in diff.mapping.pairs:
        lines.append(f"{_sdl_escape(p.output_field)}={_sdl_escape(p.output_field)}")
    return "\n".join(lines) + "\n"


def build_report_table(diff: DiffResult) -> Table:
    """差分の全行レポートTable(監査用)。

    列: 状態, キー, 各非キーペアの A/B 値ペア。
    """
    status_ja = {"only_a": "Aのみ", "only_b": "Bのみ", "changed": "変更", "same": "一致"}
    key_pairs = diff.mapping.key_pairs
    value_pairs = diff.mapping.value_pairs
    pair_index = {id(p): i for i, p in enumerate(diff.mapping.pairs)}

    columns = ["状態"]
    columns += [f"キー:{p.col_a}" for p in key_pairs]
    for p in value_pairs:
        columns.append(f"A:{p.col_a}")
        columns.append(f"B:{p.col_b}")
    columns.append("変更列")

    rows = []
    for rd in diff.rows:
        row = [status_ja[rd.status]]
        for p in key_pairs:
            i = pair_index[id(p)]
            src = rd.row_a if rd.row_a is not None else rd.row_b
            row.append(src[i] if src else "")
        changed_cols = {cd.col_a for cd in rd.cell_diffs}
        for p in value_pairs:
            i = pair_index[id(p)]
            row.append(rd.row_a[i] if rd.row_a is not None else "")
            row.append(rd.row_b[i] if rd.row_b is not None else "")
        row.append("、".join(sorted(changed_cols)) if changed_cols else "")
        rows.append(row)
    return Table(columns=columns, rows=rows, name="差分レポート")
